### ISSUE TITLE
add timestamp metric

### ISSUE THREAD

**Issue by anarcat** [voxpupuli/puppet-prometheus_reporter#84]
It looks like this exporter doesn't actually show any "timestamp" fact, that would allow monitoring to tell if a host has become stale because it hasn't (succesfully?) ran puppet in X time.

Right now, we use this to monitor for laggy hosts that have had puppet disabled for too long, in nagios. We're migrating to prometheus and this is one of the metrics missing.. .The nagios check checks both "did the catalog execute okay" and "how long ago" at once, and this exporter does the former, but not the latter.

**Comment by anarcat** [comment]
oh, nevermind, i missed the `puppet_report` timestamp, sorry for the noise.

**Comment by matejzero** [comment]
I'm using this:
```
      - alert: PuppetAgentNotRunning
        expr: time() - node_textfile_mtime_seconds{file=~"/var/lib/node_exporter/textfile_collector/puppet_.+",instance="puppet_host:9110"} > 3900
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Puppet agent isn't running on {{ $labels.host }}"
          description: |
            Puppet agent hasn't run for more than 60 min. Log in to server and check it puppet agent is running
            and if it does, run puppet agent -t --noop --debug to see why it's not applying the manifest.

```
